# Generated by Django 5.0.1 on 2024-01-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('mesaj', models.TextField()),
                ('status', models.CharField(choices=[('necitit', 'Necitit'), ('rezolvat', 'Rezolvat')], default='necitit', max_length=10)),
                ('data_inregistrare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
